layout_spectrum: 0.6953405
typography_spectrum: 0.1021505
color:
  saturation: 0.06229845
  lightness: 0.8578767
  brandStrength: 0.01708328
  rhythmicContrast: 0.6310499
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Vacation Life
