name: Vacation Life
favicon: null
layout_spectrum: 0.74913
typography_spectrum: 0.05894
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Vacation Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73224968-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0051bd'
    - '#5d8c6a'
    - '#000d1d'
    - '#425000'
    - '#b6d4f6'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
