name: Vacation Life
favicon: null
layout_spectrum: 0.6953405
typography_spectrum: 0.1021505
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Vacation Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73224968-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1F1F1F'
    - '#0465FB'
    - '#E8EAE7'
    - '#5CC6BD'
    - '#EAFF78'
  brandStrength: 0.4375
  lightness: 0.8578767
  saturation: 0.375
  rhythmicContrast: 0.6310499
purpose: []
